python train.py --config configs/EgoNeRF/ricoh/bricks/default.txt;
python train.py --config configs/EgoNeRF/ricoh/bridge/default.txt;
python train.py --config configs/EgoNeRF/ricoh/bridge_under/default.txt;
python train.py --config configs/EgoNeRF/ricoh/cat_tower/default.txt;
python train.py --config configs/EgoNeRF/ricoh/center/default.txt;
python train.py --config configs/EgoNeRF/ricoh/farm/default.txt;
python train.py --config configs/EgoNeRF/ricoh/flower/default.txt;
python train.py --config configs/EgoNeRF/ricoh/gallery_chair/default.txt;
python train.py --config configs/EgoNeRF/ricoh/gallery_pillar/default.txt;
python train.py --config configs/EgoNeRF/ricoh/garden/default.txt;
python train.py --config configs/EgoNeRF/ricoh/poster/default.txt